spring:
  cloud:
    azure.storage.blob:
      connection-string: DefaultEndpointsProtocol=https;AccountName=wmsstaweu1pre001pacdocd;AccountKey=Uii1jEyAKespEPdHPmyaVYMgCUw/kRyCjTaumcFPpfIfLuDRE30ew5ILjADwCooj/0j+rn3H5s/s+AStqVneHg==;EndpointSuffix=core.windows.net
      container-name: images
      
      
      